name: Deploy

on:
  release:
    types:
      - published

steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Publish code to NPM
    run: npm publish --access=public
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}