name: Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Store project in cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: './*'
          key: ${{ github.sha }}

  test:
    name: Run tests
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node_version: [ 14.x, 16.x ]
        protoc_version: [ 3.x ]
    steps:
      - name: Load project from cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: './*'
          key: ${{ github.sha }}

      - name: Run tests
        run: npm test

  version:
    name: Create version
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create version number
        id: version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main

  publish_package_json:
    name: Update package.json
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Update package.json
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github actions"
          npm version ${{ jobs.version.steps.version.outputs.version }}

  publish_git_tag:
    name: Push Git tag
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Push git tag
        uses: hole19/git-tag-action@master
        env:
          TAG: ${{ jobs.version.steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}

  publish_github_release:
    name: Create Github release
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Load project from cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: './*'
          key: ${{ github.sha }}

      - name: Zip project
        run: zip -r release.zip .

      - name: Create Github release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ jobs.version.steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ jobs.version.steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/gzip
